# Generated by Django 3.2.7 on 2021-10-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Farmget', 'Farmget'), ('West Razabazar', 'West Razabazar'), ('Tollabag', 'Tollabag'), ('Dhanmondi', 'Dhanmondi')], max_length=50),
        ),
    ]
